version: "3"
services: 
  db:
    image: postgres # postgres 이미지 사용
    restart: always # 
    container_name: postgres
    ports:
      - "5432:5432"
    environment: 
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - ./data/postgres/:/var/lib/postgresql/data

  server:
    build:
      context: ./Server/
    command: npm run start
    ports: 
      - "5000:5000"
    volumes: 
      - ./Server/:/usr/app
      - /usr/app/node_modules
    depends_on:
      - db

  client:
    build:
      context: ./Client/
    command: npm start
    ports:
      - "3000:3000"
    volumes:
      - ./Client/:/usr/app
      - /usr/app/node_modules
    depends_on:
      - db
      - server


    