version: "3.8"

services:
  db:
    image: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=test
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test
      - POSTGRES_INITDB_ARGS=--encoding=UTF-8

  server:
    build: server/
    command: node ./bin/www.js
    ports: 
      - 5000:5000
  
  client:
    build: client/
    command: npm start
    network_mode: host 
    ports:
      - 3000:3000
    depends_on: 
      - server db
  
